import React, { useState, useMemo } from "react";
import {
  FileText,
  Calendar as CalendarIcon,
  Filter,
  ArrowUpRight,
  ArrowDownRight,
  Printer,
  Trash2,
  TrendingUp,
  TrendingDown,
  ShieldCheck,
  CreditCard,
  RefreshCw,
  Landmark,
  Download,
} from "lucide-react";
import { useFetch } from "../../hooks/useFetch";
import { useAuthStore } from "../../store/useAuthStore";
import { formatCurrency, formatDate } from "../../utils/formatters";
import DashboardSkeleton from "../../components/skeleton/DashboardSkeleton";
import Button from "../../components/ui/Button";
import api from "../../services/api";
import toast from "react-hot-toast";

const Reports = () => {
  const user = useAuthStore((state) => state.user);
  const isSuperAdmin = user?.role === "super-admin";

  const [dateRange, setDateRange] = useState({
    startDate: new Date(new Date().getFullYear(), new Date().getMonth(), 1)
      .toISOString()
      .split("T")[0],
    endDate: new Date().toISOString().split("T")[0],
  });

  const { data, loading, refetch } = useFetch("/finance/all-transactions");

  const transactions = useMemo(() => {
    const raw = Array.isArray(data) ? data : data?.data;
    const list = Array.isArray(raw) ? raw : [];

    return list
      .filter((t) => {
        const tDate = new Date(t.date).getTime();
        const start = new Date(dateRange.startDate).getTime();
        const end = new Date(dateRange.endDate).setHours(23, 59, 59, 999);
        return tDate >= start && tDate <= end;
      })
      .sort((a, b) => new Date(b.date) - new Date(a.date));
  }, [data, dateRange]);

  const stats = useMemo(() => {
    const inflows = transactions
      .filter((t) => t.type === "deposit")
      .reduce((acc, t) => acc + t.amount, 0);
    const outflows = transactions
      .filter((t) => t.type === "expense")
      .reduce((acc, t) => acc + t.amount, 0);
    return { inflows, outflows, net: inflows - outflows };
  }, [transactions]);

  const handleDeleteTrx = async (id) => {
    if (
      !window.confirm(
        "Permanent delete? Treasury balances will be recalculated."
      )
    )
      return;
    try {
      await api.delete(`/finance/transaction/${id}`);
      toast.success("Entry removed");
      refetch();
    } catch (err) {
      toast.error("Process failed");
    }
  };

  const handlePrintStatement = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(`
      <html>
        <head>
          <title>MALIBAG_AUDIT_REPORT</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');
            body { font-family: 'Inter', sans-serif; padding: 40px; color: #0f172a; line-height: 1.5; }
            .header { display: flex; justify-content: space-between; border-bottom: 4px solid #0f172a; padding-bottom: 15px; margin-bottom: 30px; }
            .logo-section h1 { margin: 0; font-size: 20px; font-weight: 800; text-transform: uppercase; }
            .logo-section p { margin: 2px 0; font-size: 11px; color: #64748b; }
            .report-info { text-align: right; font-size: 11px; }
            .summary-box { display: flex; gap: 15px; margin-bottom: 30px; }
            .summary-card { flex: 1; padding: 15px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; }
            .summary-card div { font-size: 9px; font-weight: 800; color: #64748b; text-transform: uppercase; }
            .summary-card p { margin: 5px 0 0 0; font-size: 15px; font-weight: 800; }
            table { width: 100%; border-collapse: collapse; }
            th { text-align: left; padding: 10px; background: #0f172a; color: white; font-size: 9px; text-transform: uppercase; }
            td { padding: 10px; border-bottom: 1px solid #e2e8f0; font-size: 10px; }
            .amt { font-weight: 800; }
            .in { color: #16a34a; }
            .out { color: #dc2626; }
            .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #e2e8f0; font-size: 9px; color: #94a3b8; display: flex; justify-content: space-between; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="logo-section">
              <h1>Malibag Shomiti Registry</h1>
              <p>Treasury Audit Division</p>
            </div>
            <div class="report-info">
              <p>Period: ${formatDate(dateRange.startDate)} - ${formatDate(
      dateRange.endDate
    )}</p>
              <p>Generated by: ${user?.name}</p>
            </div>
          </div>
          <div class="summary-box">
            <div class="summary-card"><div>Inflows</div><p style="color:#16a34a">৳${stats.inflows.toLocaleString()}</p></div>
            <div class="summary-card"><div>Outflows</div><p style="color:#dc2626">৳${stats.outflows.toLocaleString()}</p></div>
            <div class="summary-card" style="background:#0f172a; color:white;"><div>Net Performance</div><p>৳${stats.net.toLocaleString()}</p></div>
          </div>
          <table>
            <thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th style="text-align:right">Value</th></tr></thead>
            <tbody>
              ${transactions
                .map(
                  (t) => `
                <tr>
                  <td>${new Date(t.date).toLocaleDateString("en-GB")}</td>
                  <td><strong>${t.user?.name || "Internal"}</strong><br/>${
                    t.remarks || "-"
                  }</td>
                  <td>${t.category.toUpperCase()}</td>
                  <td>${t.type.toUpperCase()}</td>
                  <td style="text-align:right" class="amt ${
                    t.type === "deposit" ? "in" : "out"
                  }">
                    ${
                      t.type === "deposit" ? "+" : "-"
                    } ৳${t.amount.toLocaleString()}
                  </td>
                </tr>`
                )
                .join("")}
            </tbody>
          </table>
          <div class="footer"><span>Printed on: ${new Date().toLocaleString()}</span></div>
          <script>window.print(); window.onafterprint = function() { window.close(); };</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  if (loading) return <DashboardSkeleton />;

  return (
    <div className="max-w-7xl mx-auto space-y-6 animate-in fade-in duration-500 pb-20">
      {/* --- Header --- */}
      <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center gap-4">
          <div className="p-2.5 bg-slate-900 text-white rounded-lg shadow-md">
            <ShieldCheck size={20} />
          </div>
          <div>
            <h1 className="text-lg font-bold text-slate-900 tracking-tight">
              Audit Registry
            </h1>
            <p className="text-[11px] text-slate-500 font-medium">
              Fiscal history tracking
            </p>
          </div>
        </div>

        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full lg:w-auto">
          {/* Date Container: Stacks on mobile, inline on desktop */}
          <div className="flex flex-1 bg-slate-50 p-1 rounded-lg border border-slate-100 no-print">
            <input
              type="date"
              className="bg-transparent flex-1 px-2 py-1 text-[11px] font-bold text-slate-700 outline-none min-w-[110px]"
              value={dateRange.startDate}
              onChange={(e) =>
                setDateRange({ ...dateRange, startDate: e.target.value })
              }
            />
            <div className="w-px h-4 bg-slate-300 self-center mx-1 flex-shrink-0" />
            <input
              type="date"
              className="bg-transparent flex-1 px-2 py-1 text-[11px] font-bold text-slate-700 outline-none min-w-[110px]"
              value={dateRange.endDate}
              onChange={(e) =>
                setDateRange({ ...dateRange, endDate: e.target.value })
              }
            />
          </div>

          {/* Button: Full width on mobile, auto width on desktop */}
          <button
            onClick={handlePrintStatement}
            className="flex items-center justify-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg font-bold text-[10px] uppercase tracking-widest hover:bg-slate-800 transition-all active:scale-95 whitespace-nowrap"
          >
            <Printer size={14} /> Export
          </button>
        </div>
      </div>

      {/* --- KPI Grid --- */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          {
            label: "Aggregate Inflows",
            val: stats.inflows,
            icon: TrendingUp,
            color: "emerald",
            sub: "Total Deposits",
          },
          {
            label: "Aggregate Outflows",
            val: stats.outflows,
            icon: TrendingDown,
            color: "rose",
            sub: "Total Expenses",
          },
          {
            label: "Fiscal Net Total",
            val: stats.net,
            icon: RefreshCw,
            color: "blue",
            sub: "Performance",
          },
        ].map((kpi, i) => (
          <div
            key={i}
            className="bg-white p-5 rounded-xl border border-slate-200 flex items-center justify-between shadow-sm"
          >
            <div>
              <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">
                {kpi.label}
              </p>
              <p className="text-xl font-black text-slate-900">
                {formatCurrency(kpi.val)}
              </p>
              <p className="text-[9px] font-bold text-slate-400 uppercase mt-1">
                {kpi.sub}
              </p>
            </div>
            <div
              className={`p-3 bg-${kpi.color}-50 text-${kpi.color}-600 rounded-xl`}
            >
              <kpi.icon size={18} />
            </div>
          </div>
        ))}
      </div>

      {/* --- Transaction Table --- */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-4 border-b border-slate-100 bg-slate-50/30 flex items-center gap-2">
          <Landmark size={14} className="text-slate-400" />
          <h2 className="text-[10px] font-black text-slate-500 uppercase tracking-widest">
            Digital Ledger Registry
          </h2>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-white border-b border-slate-100">
                <th className="px-6 py-4 text-[9px] font-black text-slate-400 uppercase tracking-widest">
                  Post Date / Details
                </th>
                <th className="px-6 py-4 text-[9px] font-black text-slate-400 uppercase tracking-widest">
                  Origin Source
                </th>
                <th className="px-6 py-4 text-[9px] font-black text-slate-400 uppercase tracking-widest">
                  Classification
                </th>
                <th className="px-6 py-4 text-[9px] font-black text-slate-400 uppercase tracking-widest text-right">
                  Value
                </th>
                {isSuperAdmin && (
                  <th className="px-6 py-4 text-[9px] font-black text-slate-400 uppercase tracking-widest text-center no-print">
                    Sync
                  </th>
                )}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {transactions.map((t, idx) => (
                <tr
                  key={idx}
                  className="hover:bg-slate-50/50 transition-colors group"
                >
                  <td className="px-6 py-4">
                    <div className="flex items-start gap-3">
                      <div
                        className={`mt-0.5 p-1.5 rounded-lg ${
                          t.type === "deposit"
                            ? "bg-emerald-50 text-emerald-600"
                            : "bg-rose-50 text-rose-600"
                        }`}
                      >
                        {t.type === "deposit" ? (
                          <ArrowUpRight size={14} />
                        ) : (
                          <ArrowDownRight size={14} />
                        )}
                      </div>
                      <div>
                        <p className="text-xs font-bold text-slate-800 line-clamp-1">
                          {t.remarks || "Treasury Post"}
                        </p>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-tighter mt-0.5">
                          {formatDate(t.date)}
                        </p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="space-y-1">
                      <p className="text-[11px] font-black text-slate-700">
                        {t.user?.name || "Society Registry"}
                      </p>
                      {t.user?.phone && (
                        <div className="flex items-center gap-1 text-[9px] font-bold text-slate-400 uppercase">
                          <CreditCard size={10} /> ID: {t.user.phone}
                        </div>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="space-y-1">
                      <span className="inline-block px-2 py-0.5 bg-slate-100 text-slate-600 text-[9px] font-black rounded uppercase tracking-widest border border-slate-200">
                        {t.category.replace("_", " ")}
                      </span>
                      {t.subcategory && (
                        <p className="text-[10px] font-bold text-blue-500 pl-1 tracking-tight">
                          → {t.subcategory}
                        </p>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <p
                      className={`text-[13px] font-black ${
                        t.type === "deposit"
                          ? "text-emerald-600"
                          : "text-rose-600"
                      }`}
                    >
                      {t.type === "deposit" ? "+" : "-"}
                      {formatCurrency(t.amount)}
                    </p>
                  </td>
                  {isSuperAdmin && (
                    <td className="px-6 py-4 text-center no-print">
                      <button
                        onClick={() => handleDeleteTrx(t._id)}
                        className="p-2 text-slate-300 hover:text-rose-600 hover:bg-rose-50 rounded-lg opacity-0 group-hover:opacity-100 transition-all"
                      >
                        <Trash2 size={16} />
                      </button>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
          {transactions.length === 0 && (
            <div className="py-20 text-center">
              <FileText size={40} className="mx-auto text-slate-200 mb-3" />
              <p className="text-[11px] font-black text-slate-400 uppercase tracking-widest">
                No matching registry entries found
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Reports;
